[package]
name = "zkml"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 3

[dependencies]
bitvec = "1.0.1"
halo2 = { git="https://github.com/privacy-scaling-explorations/halo2", package="halo2", rev="c7e42e41f8141745ba0b90213438f240d55cb347" }
halo2_gadgets = { git="https://github.com/privacy-scaling-explorations/halo2", package="halo2_gadgets", rev="c7e42e41f8141745ba0b90213438f240d55cb347" }
halo2_proofs = { git="https://github.com/privacy-scaling-explorations/halo2", package="halo2_proofs", rev="c7e42e41f8141745ba0b90213438f240d55cb347" }
lazy_static = "1.4.0"
ndarray = "0.15.6"
num-bigint = "0.4.3"
once_cell = "1.15.0"
rand = "0.8.5"
rmp-serde = "1.1.1"
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.85"

